# Generated by Django 5.2.3 on 2025-06-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analytics',
            new_name='analytics_organiz_347a1d_idx',
            old_name='analytics_organization_analytics_type_idx',
        ),
        migrations.RenameIndex(
            model_name='analytics',
            new_name='analytics_period__bf3ccc_idx',
            old_name='analytics_period_start_period_end_idx',
        ),
        migrations.RenameIndex(
            model_name='analytics',
            new_name='analytics_analyti_cd574d_idx',
            old_name='analytics_analytics_type_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='dashboards_organiz_78cdd2_idx',
            old_name='dashboards_organization_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='dashboards_is_defa_824dc6_idx',
            old_name='dashboards_is_default_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='dashboards_created_2059ca_idx',
            old_name='dashboards_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='exports_organiz_dcb04a_idx',
            old_name='exports_organization_status_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='exports_export__4d4395_idx',
            old_name='exports_export_type_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='exports_created_5d2fc6_idx',
            old_name='exports_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='exports_status_c44cc2_idx',
            old_name='exports_status_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_organiz_987b4c_idx',
            old_name='reports_organization_report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_is_acti_d93e66_idx',
            old_name='reports_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_is_sche_e54d60_idx',
            old_name='reports_is_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_created_898775_idx',
            old_name='reports_created_by_idx',
        ),
    ]
