# Generated by Django 5.2.3 on 2025-07-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('reports', '0002_rename_analytics_organization_analytics_type_idx_analytics_organiz_347a1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.organization'),
        ),
    ]
