# Generated by Django 5.2.3 on 2025-06-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_fbfd51_idx',
            old_name='audit_logs_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_organiz_af0d8d_idx',
            old_name='audit_logs_organization_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_audit_t_75cd0e_idx',
            old_name='audit_logs_audit_type_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_content_b0ef47_idx',
            old_name='audit_logs_content_type_object_id_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='system_logs_level_245244_idx',
            old_name='system_logs_level_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='system_logs_module_ac9b9d_idx',
            old_name='system_logs_module_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='system_logs_created_2e006d_idx',
            old_name='system_logs_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='system_logs_user_id_85bc8b_idx',
            old_name='system_logs_user_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='system_logs_organiz_8e2377_idx',
            old_name='system_logs_organization_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_user_id_c742e0_idx',
            old_name='user_activities_user_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_organiz_11071e_idx',
            old_name='user_activities_organization_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_activit_534635_idx',
            old_name='user_activities_activity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_is_succ_bc11d2_idx',
            old_name='user_activities_is_successful_idx',
        ),
    ]
