# Generated by Django 5.2.3 on 2025-07-16 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('logs', '0002_rename_audit_logs_user_created_at_idx_audit_logs_user_id_fbfd51_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_user_id_fbfd51_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_organiz_af0d8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_audit_t_75cd0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_content_b0ef47_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='audit_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_values',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('PASSWORD_RESET', 'Password Reset'), ('ORGANIZATION_CREATE', 'Organization Created'), ('ORGANIZATION_UPDATE', 'Organization Updated'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted')], default='LOGIN', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization'], name='audit_logs_organiz_b941b8_idx'),
        ),
    ]
