# Generated by Django 5.2.3 on 2025-06-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bank',
            new_name='banks_name_f09ef4_idx',
            old_name='banks_name_idx',
        ),
        migrations.RenameIndex(
            model_name='bank',
            new_name='banks_bank_ty_a79500_idx',
            old_name='banks_bank_type_idx',
        ),
        migrations.RenameIndex(
            model_name='bank',
            new_name='banks_is_acti_f48c7a_idx',
            old_name='banks_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='casestatus',
            new_name='case_status_name_06494e_idx',
            old_name='case_statuses_name_idx',
        ),
        migrations.RenameIndex(
            model_name='casestatus',
            new_name='case_status_is_acti_0dc7f8_idx',
            old_name='case_statuses_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cities_name_a7bf2e_idx',
            old_name='cities_name_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cities_state_i_235f02_idx',
            old_name='cities_state_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cities_is_acti_a959ab_idx',
            old_name='cities_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='nbfc',
            new_name='nbfcs_name_080a51_idx',
            old_name='nbfcs_name_idx',
        ),
        migrations.RenameIndex(
            model_name='nbfc',
            new_name='nbfcs_nbfc_ty_8eab30_idx',
            old_name='nbfcs_nbfc_type_idx',
        ),
        migrations.RenameIndex(
            model_name='nbfc',
            new_name='nbfcs_is_acti_80f9b5_idx',
            old_name='nbfcs_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmasterdata',
            new_name='organizatio_organiz_b5bc5d_idx',
            old_name='organization_master_data_organization_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmasterdata',
            new_name='organizatio_is_acti_2dd738_idx',
            old_name='organization_master_data_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='producttype',
            new_name='product_typ_name_bfc641_idx',
            old_name='product_types_name_idx',
        ),
        migrations.RenameIndex(
            model_name='producttype',
            new_name='product_typ_is_acti_fe4a4c_idx',
            old_name='product_types_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='state',
            new_name='states_name_9db832_idx',
            old_name='states_name_idx',
        ),
        migrations.RenameIndex(
            model_name='state',
            new_name='states_code_65eed8_idx',
            old_name='states_code_idx',
        ),
        migrations.RenameIndex(
            model_name='state',
            new_name='states_is_acti_acbfdd_idx',
            old_name='states_is_active_idx',
        ),
    ]
