# Generated by Django 5.2.3 on 2025-06-29 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_name_5cd1d4_idx',
            old_name='organizations_name_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_busines_959b63_idx',
            old_name='organizations_business_type_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_is_acti_bdc355_idx',
            old_name='organizations_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_usernam_baeb4b_idx',
            old_name='users_username_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='users_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_organiz_ca9165_idx',
            old_name='users_organization_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_acti_847b48_idx',
            old_name='users_is_active_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
        ),
    ]
