# Generated by Django 5.2.3 on 2025-06-29 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='form_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='dynamicformschema',
            new_name='dynamic_for_organiz_394706_idx',
            old_name='dynamic_form_schemas_organization_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamicformschema',
            new_name='dynamic_for_created_70fca2_idx',
            old_name='dynamic_form_schemas_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='form_entrie_organiz_09d256_idx',
            old_name='form_entries_organization_employee_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='form_entrie_form_sc_cce553_idx',
            old_name='form_entries_form_schema_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='form_entrie_is_comp_807bbf_idx',
            old_name='form_entries_is_completed_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='form_entrie_is_out__b41364_idx',
            old_name='form_entries_is_out_of_tat_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='form_entrie_created_8e6eb2_idx',
            old_name='form_entries_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='formfield',
            new_name='form_fields_organiz_c07160_idx',
            old_name='form_fields_organization_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='formfield',
            new_name='form_fields_field_t_d3aee2_idx',
            old_name='form_fields_field_type_idx',
        ),
        migrations.AlterField(
            model_name='dynamicformschema',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='form_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forms.formentry'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dynamicformschema',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_schemas', to='forms.organization'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_entries', to='forms.organization'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='forms.organization'),
        ),
    ]
