# Generated by Django 5.2.3 on 2025-06-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('forms', '0002_fileattachment_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_entries', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='dynamicformschema',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_schemas', to='accounts.organization'),
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='dynamicformschema',
            name='unique_schema_name_per_organization',
        ),
        migrations.RemoveConstraint(
            model_name='formfield',
            name='unique_field_name_per_organization',
        ),
        migrations.RemoveIndex(
            model_name='formentry',
            name='form_entrie_is_out__b41364_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamicformschema',
            new_name='forms_dynam_organiz_3ba247_idx',
            old_name='dynamic_for_organiz_394706_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamicformschema',
            new_name='forms_dynam_created_4d765f_idx',
            old_name='dynamic_for_created_70fca2_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='forms_forme_organiz_be1043_idx',
            old_name='form_entrie_organiz_09d256_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='forms_forme_form_sc_45d48b_idx',
            old_name='form_entrie_form_sc_cce553_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='forms_forme_is_comp_a59b1c_idx',
            old_name='form_entrie_is_comp_807bbf_idx',
        ),
        migrations.RenameIndex(
            model_name='formentry',
            new_name='forms_forme_created_24271d_idx',
            old_name='form_entrie_created_8e6eb2_idx',
        ),
        migrations.RenameIndex(
            model_name='formfield',
            new_name='forms_formf_organiz_5614ab_idx',
            old_name='form_fields_organiz_c07160_idx',
        ),
        migrations.RenameIndex(
            model_name='formfield',
            new_name='forms_formf_field_t_001081_idx',
            old_name='form_fields_field_t_d3aee2_idx',
        ),
        migrations.RemoveField(
            model_name='formentry',
            name='file_attachments',
        ),
        migrations.RemoveField(
            model_name='formentry',
            name='is_out_of_tat',
        ),
        migrations.AlterField(
            model_name='dynamicformschema',
            name='fields_definition',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='form_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('STRING', 'String'), ('ALPHANUMERIC', 'Alphanumeric'), ('SYMBOLS_ALPHANUMERIC', 'Symbols + Alphanumeric'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='validation_rules',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformschema',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='dynamicformschema',
            table=None,
        ),
        migrations.AlterModelTable(
            name='formentry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='formfield',
            table=None,
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
