# Generated by Django 5.2.3 on 2025-07-09 08:27

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formentry_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to=utils.storage.get_file_upload_path),
        ),
    ]
