# Generated by Django 5.2.3 on 2025-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_add_form_field_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformschema',
            name='tat_hours_limit',
            field=models.PositiveIntegerField(default=24, help_text='TAT hours limit for this form schema'),
        ),
    ]
