# Generated by Django 5.2.3 on 2025-07-17 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('forms', '0006_add_tat_hours_limit_to_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='agency_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing agency ID', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='formentry',
            index=models.Index(fields=['agency_id'], name='forms_forme_agency__aa9665_idx'),
        ),
    ]
