# Generated by Django 5.2.3 on 2025-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formentry_agency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldfile',
            name='s3_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
