# Generated by Django 5.2.3 on 2025-07-19 12:42

import forms.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_fix_case_id_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='case_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing case ID per organization', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='formentry',
            unique_together={('organization', 'case_id')},
        ),
    ]
