# Generated by Django 5.2.3 on 2025-07-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_update_formfieldfile_model'),
        ('forms', '0011_update_case_id_field'),
    ]

    operations = [
    ]
