# Generated by Django 5.2.3 on 2025-07-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('forms', '0012_merge_20250720_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_case_id', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_id_sequence', to='accounts.organization')),
            ],
            options={
                'db_table': 'forms_case_id_sequence',
            },
        ),
    ]
