# Generated by Django 5.2.3 on 2025-07-21 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_organizations_name_idx_organizatio_name_5cd1d4_idx_and_more'),
        ('forms', '0013_caseidsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseidsequence',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='formentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formentry',
            name='entry_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing entry ID per organization', null=True),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='case_id',
            field=models.PositiveIntegerField(blank=True, help_text='Case ID for grouping', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='formentry',
            unique_together={('organization', 'entry_id')},
        ),
        migrations.AddIndex(
            model_name='formentry',
            index=models.Index(fields=['entry_id'], name='forms_forme_entry_i_24418a_idx'),
        ),
        migrations.DeleteModel(
            name='CaseIdSequence',
        ),
    ]
