# Generated by Django 5.2.3 on 2025-09-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_remove_caseidsequence_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformschema',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('STRING', 'String'), ('ALPHANUMERIC', 'Alphanumeric'), ('SYMBOLS_ALPHANUMERIC', 'Symbols + Alphanumeric'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SELECT', 'Select/Dropdown'), ('IMAGE_UPLOAD', 'Image Upload'), ('DOCUMENT_UPLOAD', 'Document Upload')], max_length=20),
        ),
    ]
